### ISSUE TITLE
Useless transpose executed in pairwise_alignment module

### ISSUE THREAD

**Issue by thomasbazeille** [Parietal-INRIA/fmralign#17]
This is mostly a clarity of code issue and also it could gain a little computations.

For now, fmralign.utils.load_img make a transposition after masking the images. It is useless for most of operations that are performed next and creates the need for doing some additional transpositions.
For example for alignment methods.

We could remove this first transpose but it it would need to make modifications in most functions that use or act on X / Y : utils.piecewise_transform, utils.load_img, fit_one_parcellation, fit_one_piece, generate_Xi_Yi and make_parcellation.

**Comment by bthirion** [comment]
+1 for this change. 
the sooner the better.

**Comment by thomasbazeille** [comment]
Closing, solved in #29
