### ISSUE TITLE
make POT and optional dependency

### ISSUE THREAD

**Issue by bthirion** [Parietal-INRIA/fmralign#18]
Because it is harder to install (e.g. fails with cython 0.29). I had to upgrade cython to get it....

**Comment by thomasbazeille** [comment]
The problem seem to occur specifically in anaconda, the quickfix is to run
`conda install --upgrade cython`

It is related to this issue : https://github.com/rflamary/POT/issues/59 but when I tried replicating the problem in a fresh environment I was unable to reproduce it, `pip install fmralign` was running smoothly.

**Comment by bthirion** [comment]
Yep, but users son't always have a fresh environment, and they may really be bothered by such errors (that are fairly unfriendly to non-experts). This is the reason why Nilearn has no dependency on Cython !
Making POT an optional dependency is not complicated I think, and you can probably get most of the hyperalignment benefits with cheaper methods than POT.

**Comment by agramfort** [comment]
what part of POT do you need? maybe you can just take the plain numpy code
to avoid the strong dep on a package that is pretty bleeding edge...

>

**Comment by thomasbazeille** [comment]
The major method we use for now is the log-stabilized sinkhorn, you right maybe we don't need to have the full dependency for that. I did not consider taking the relevant code to not duplicate test and maintenance but maybe it is less costly after all than being dependent on POT.

Will make the dependence optional for the time being.

**Comment by thomasbazeille** [comment]
Solved by #23
