### ISSUE TITLE
Continous Integration improvement specification

### ISSUE THREAD

**Issue by thomasbazeille** [Parietal-INRIA/fmralign#28]
@bthirion, you requested that we integrate Travis CI but which feature did you have specifically in mind ?

When discussing the option with Kshitij,  he told me that almost every tool provided by Travis was provided by Circle CI as well, so we could only improve our use of Circle CI.

He proposed also to use azure pipelines instead which are now used by scikit-learn and by nilearn.

**Comment by bthirion** [comment]
If CircleCI  soes everything we need, then let's stick to CirceCI only. For now, it is broken...

Please no azure pipeline for the moment.
