### ISSUE TITLE
Explanation for template alignment

### ISSUE THREAD

**Issue by jaysonjeg** [Parietal-INRIA/fmralign#54]
In fmralign/template_alignment.py, in function _create_template:

In this code, all subjects are aligned simultaneously to the mean image (across subjects). This is done iteratively (twice by default). I was wondering if you had any intuition about why this is a good way to find a reasonable template. For example, I don't fully understand the rationale behind the second iteration. 

It's an interesting contrast to the original Haxby iterative method

**Comment by emdupre** [comment]
Hi @jaysonjeg  --

Thanks for reaching out ! 

The rationale is unpacked more in this paper, in particular in Section 2: Theory, _Template inference_: https://hal.science/hal-02278663

You can also find experimental results in the same paper supporting this approach !

HTH,

Elizabeth

**Comment by bthirion** [comment]
The idea is that after a first pass, the template can be refined, leading to improved alignments in turn, and so on. In practice, two iterations of this process seem to be sufficient.

**Comment by jaysonjeg** [comment]
That was clarifying. Thank you

**Comment by emdupre** [comment]
Closing as resolved ; please open another issue if you have additional questions on this point !
