### ISSUE TITLE
Improve parcellation API and capabilities

### ISSUE THREAD

**Issue by thomasbazeille** [Parietal-INRIA/fmralign#6]
For now :
- parcellation by default is k-means,
- ward is not tested,

Possible improvements:
1. both should rely on Parcellation object of nilearn (for now k-means doesn't)
2. an easy option to save parcellation
3. tests, maybe an example as well to check and discuss the impact of parcellation method on alignment proficiency

**Comment by thomasbazeille** [comment]
In fact, parcellation method should be usable as well in template module directly. Maybe it should be moved to .utils

**Comment by bthirion** [comment]
Agreed.
Also a technical details: smooth the data prior to k-means application to favour spatially compact clusters.

**Comment by thomasbazeille** [comment]
While solving this issue, we should also discuss the heuristics used to select the data for parcellation in various usecases. I'll try to do some experiments on joint clustering before that

**Comment by thomasbazeille** [comment]
Be able to input a given atlas / parcellation, as a Niimg instead of a parcellation method would be a nice feature as well.

**Comment by thomasbazeille** [comment]
@bthirion do you think i should use smoothing prior to Ward and ReNA as well or only for k-means ? 
Does fwhm of 5 mm seem ok for such a purpose ?

**Comment by bthirion** [comment]
Normally, before kmeans only.
fwhm = 5 or 10 (try it).
B

**Comment by thomasbazeille** [comment]
Closing after merging of #29 that include all that
