### ISSUE TITLE
Implement a diagonal transformation, projecting X on Y through voxel signal scaling

### ISSUE THREAD

**Issue by thomasbazeille** [Parietal-INRIA/fmralign#7]

**Comment by bthirion** [comment]
I was thinking that scaling could be done after any estimator, though for some, such as ridge it makes no sense.

**Comment by bthirion** [comment]
A related question is: compare rescaled ortogonal transform with bootstraraped orthogonal transform: if bootstrap brings nothing more than scaling, then it is essentially useless !

**Comment by thomasbazeille** [comment]
> I was thinking that scaling could be done after any estimator, though for some, such as ridge it makes no sense.

You mean, first a transform (for example orthogonal, or a permutation) and then a voxelwise projection of the prediction on the target ? I fear if both are learnt consecutively on the train set, it will just foster overfit. This also makes our models more complex. 

What I propose is first to make projection available as a separate estimator to see how much the shrinkage of the signal it induces contributes to improve the prediction metrics and afterwards if needed to make it available after every model.

In the meantime, it will always be possible to chain the estimators if you need it for example :
`orthogonal.fit(X, Y)
X_transformed = orthogonal.transform(X)
diagonal.fit(X_transformed, Y)
X_transformed_rescaled = diagonal.transform(orthogonal.transform(X))`

**Comment by bthirion** [comment]
Well it makes sense for methods like permutation.
However, i like the idea of chaining estimators explicitly.
