### ISSUE TITLE
Update imports from ```nilearn.input_data.masker_validation ```to ```nilearn.decoding.decoders ```

### ISSUE THREAD

**Issue by denisfouchard** [Parietal-INRIA/fmralign#71]
![image](https://github.com/Parietal-INRIA/fmralign/assets/95576336/c355b8f6-6c72-4759-8007-2fdcf327abb3)

![image](https://github.com/Parietal-INRIA/fmralign/assets/95576336/60acd48a-60fd-4ca4-af7f-28ee74e5507c)

**Comment by denisfouchard** [comment]
![image](https://github.com/Parietal-INRIA/fmralign/assets/95576336/70b74d33-83b0-413e-b7a2-49819f71f7d7)

Also, there should be no argument to the ```Memory```constructor call, as it fails during ```PairwiseAlignment``` initialization

**Comment by emdupre** [comment]
Hi @denisfouchard , thanks for reporting ! Could you confirm which version of fmralign you're using ? I've fixed most of these issues, but there hasn't yet been an updated release. You should, though, be able to pip install from the latest git commit.

**Comment by bthirion** [comment]
`pip install -e .` from the Github repo.

**Comment by pbarbarant** [comment]
Closed with the new release.
