### ISSUE TITLE
Potential fugw integration

### ISSUE THREAD

**Issue by emdupre** [Parietal-INRIA/fmralign#77]
> I presume that FastSRM being a more "reputable" package it is ok to keep it standalone.

> How about fugw btw ? Would it be nice to integrate it to compare to basic OT method ? Maybe @alexisthual ?

_mentioned by @denisfouchard in #70 ([comment](https://github.com/Parietal-INRIA/fmralign/pull/70#issuecomment-1906080329))_

**Comment by alexisthual** [comment]
In my opinion, there is no theoretical impediment to integrating fugw in this repo :blush: 
Things would probably be easier if I cut a new release of fugw beforehand, so that you can benefit from the latest features and use a more stable API.

**Comment by alexisthual** [comment]
`fugw` 0.1.1 is just out, the API should be stable and ready to use!

**Comment by pbarbarant** [comment]
I have a documented wrapper that I regularly use for personal experiments, I'll try to clean it up for an upcoming PR :)
