### ISSUE TITLE
Compatibility with Nilearn 0.10.3

### ISSUE THREAD

**Issue by bthirion** [Parietal-INRIA/fmralign#78]
Some imports are broken now
`from nilearn.datasets._utils import fetch_files, _get_dataset_dir`
in `fetch_example_data.py`

**Comment by emdupre** [comment]
I believe this is as simple as re-applying [this commit](https://github.com/Parietal-INRIA/fmralign/commit/0e1ce05e28f7ec8fe8dde307b9b78f1fd6a6f945), but will confirm.
