### ISSUE TITLE
Keep a fixed parcellation when computing templates

### ISSUE THREAD

**Issue by pbarbarant** [Parietal-INRIA/fmralign#86]
`_align_images_to_template` instantiates a bunch of `PairwiseAlignment` estimators, each of which generate their own parcellation of the data. I would argue that a single parcellation should be computed once when instantiating the template for the following reasons:

1. Obvious speed gains;
2. The whole dataset could be used to derive more precise regions (especially for ward and kmeans), rather than working with pairs of subjects;
3. Better control when fitting the template.

Best,
PL

**Comment by bthirion** [comment]
Fully agree with that. 
We've spent too much time on pairwise alignments ...
