### ISSUE TITLE
[DOC] Update the doc theme

### ISSUE THREAD

**Issue by emdupre** [Parietal-INRIA/fmralign#94]
The theme for the built docs is a bit clunky ; I'd suggest we update to [pydata-sphinx-theme](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/install.html), following MNE and sklearn, or [furo](https://pradyunsg.me/furo/), following nilearn.

**Comment by emdupre** [comment]
furo it is then (!), unless @bthirion  has a strong opinion otherwise 😸

**Comment by bthirion** [comment]
Good with me, thx !
